version: "3.8"

services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    image: vjepspark:latest
    container_name: vjepspark
    runtime: nvidia
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
      - TRANSFORMERS_NO_TORCHAO=1
    volumes:
      - ${HOME}/.pytorch-container-data:/workspace
      - /tmp:/tmp
    ipc: host
    shm_size: "16g"
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
