version: '3.8'

services:
  rtsp-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtsp-consumer-udp
    runtime: nvidia
    network_mode: host  # Critical for UDP streaming
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GST_DEBUG=2
      - PYTHONUNBUFFERED=1
      - RTSP_URL=udp://100.94.31.62:8554
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["/app/run_consumer.sh"]
