version: '3.8'

services:
  rtsp-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtsp-consumer-minimal
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GST_DEBUG=2
      - PYTHONUNBUFFERED=1
      - RTSP_URL=udp://192.168.0.237:8554
    restart: unless-stopped
    command: python3 rtsp_consumer.py --url udp://192.168.0.237:8554
