version: '3.8'

services:
  rtsp-consumer:
    build:
      context: ..
      dockerfile: consumer/Dockerfile
    container_name: rtsp-consumer-dgx
    runtime: nvidia  # Enable NVIDIA GPU access
    network_mode: host  # Use host networking for UDP access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GST_DEBUG=2
      - PYTHONUNBUFFERED=1
      - RTSP_URL=udp://127.0.0.1:8554  # UDP stream URL
      - VJEPA_SERVICE_URL=http://localhost:8000  # VJEPA2 inference service URL
    volumes:
      # Mount output directory for saving frames
      - ./output:/app/output
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    # Resource limits for DGX Spark
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import gi; gi.require_version('Gst', '1.0'); from gi.repository import Gst; Gst.init(None)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
